baseurl      = "https://digitalitility.com"
title        = "Digitalitility"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

googleAnalytics = "G-PDX3FWK8T1"

[permalinks]
  posts = "/posts/:year/:month/:title/"

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "of Stefan Schwaha"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "art portfolio of Stefan Schwaha"
  keywords = "homepage, blog"
  images = [""]

enableThemeToggle = true

[author]
  name = "Stefan Schwaha"

[params.footer]
  trademark = true
  author = true
  copyright = true

[[params.social]]
  name = "github"
  url = "https://github.com/sektionschef"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/sektionschef"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/stefanschwaha/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.logo]
  logoMark     = ">"

[languages]
  [languages.en]
    title = "Art projects"
    subtitle = "of Stefan Schwaha"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Digitalitility"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
    identifier = "portfolio"
    name       = "Portfolio"
    url        = "posts"

  [[menu.main]]
    identifier = "donation"
    name       = "Donation"
    url        = "donation/"
  
[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params.portrait]
   path     = "stefan schwaha 201906.jpg"
   alt      = "Stefan Schwaha Portrait"
   maxWidth = "80px"